version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: tracking_service_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: tracking_service_db
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
