spring:
  datasource:
    url: jdbc:mysql://localhost:3307/tracking_service_db?serverTimezone=America/Sao_Paulo
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 5000
      keepalive-timeout: 30000
      leak-detection-threshold: 15000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        auto-startup: true
        missing-queues-fatal: false
        concurrency: 5
        max-concurrency: 10

  task:
    scheduling:
      enabled: true

  cache:
    type: caffeine

  main:
    allow-bean-definition-overriding: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  url: jdbc:mysql://localhost:3307/tracking_service_db?serverTimezone=America/Sao_Paulo
  user: root
  password: 1234567

server:
  port: 8080

external-apis:
  nager-date-url: "https://date.nager.at/api/v3/publicholidays"
  dog-api-url: "https://dogapi.dog/api/v2/facts?limit=1"

batch:
  tracking-events:
    interval-ms: 60000
    batch-size: 5000

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health"
  metrics:
    enable:
      hikari: true
