spring:
  datasource:
    url: jdbc:mysql://localhost:3307/tracking_service_db?serverTimezone=UTC
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        auto-startup: true
        missing-queues-fatal: false

  main:
    allow-bean-definition-overriding: true

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  url: jdbc:mysql://localhost:3307/tracking_service_db?serverTimezone=UTC
  user: root
  password: 1234567

server:
  port: 8080

external-apis:
  nager-date-url: "https://date.nager.at/api/v3/publicholidays/2025/BR"
  dog-api-url: "https://dogapi.dog/api/v2/facts?limit=1"

